### ISSUE TITLE
test_provider_vm_create Fails for Chameleon

### ISSUE THREAD

**Issue by joshua-m-baker** [cloudmesh/cloudmesh-openstack#4]
Creating a VM in Chameleon cloud works from the command line but fails when being run in the cloudmesh-cloud/tests/cloud test08. The create_server function fails because of an invalid 'name', but it appears to be correct. 

Info: 
```
# ----------------------------------------------------------------------
# Create Server
# ----------------------------------------------------------------------
    Cloud:    chameleon
    Name:     test-josh-vm-2
    Label:    test-josh-vm-2
    User:     cc
    IP:       129.114.26.58
    Image:    CC-Ubuntu18.04
    Size:     m1.medium
    Network:  e01ee12e-fd22-4b21-a050-d3e015f42bb1
    Public:   True
    Key:      josh
    Location: None
    Timeout:  360
    Secgroup: None
    Group:    cloudmesh
    Groups:   ['cloudmesh']
```

```Trace:
Traceback (most recent call last):
      File "/home/josh/dev/cloud/cloudmesh-openstack/cloudmesh/openstack/compute/Provider.py", line 1043, in create
        server = self.cloudman.create_server(name,
      File "<decorator-gen-4>", line 2, in create_server
      File "/home/josh/ENV3/lib/python3.8/site-packages/openstack/cloud/_utils.py", line 378, in func_wrapper
        return func(*args, **kwargs)
      File "/home/josh/ENV3/lib/python3.8/site-packages/openstack/cloud/_compute.py", line 933, in create_server
        data = proxy._json_response(
      File "/home/josh/ENV3/lib/python3.8/site-packages/openstack/proxy.py", line 543, in _json_response
        exceptions.raise_from_response(response, error_message=error_message)
      File "/home/josh/ENV3/lib/python3.8/site-packages/openstack/exceptions.py", line 234, in raise_from_response
        raise cls(
    openstack.exceptions.BadRequestException: BadRequestException: 400: Client Error for url: https://kvm.tacc.chameleoncloud.org:8774/v2.1/servers, An invalid 'name' value was provided. The name must be: printable characters. Can not start or end with whitespace.

BadRequestException: 400: Client Error for url: https://kvm.tacc.chameleoncloud.org:8774/v2.1/servers, An invalid 'name' value was provided. The name must be: printable characters. Can not start or end with whitespace.
FAILED
```

**Comment by joshua-m-baker** [comment]
Steps to reproduce:

```
cd cloudmesh-cloud/
cms set cloud=chameleon
pytest -v --capture=no tests/cloud/test_08_vm_provider.py 
```

**Comment by laszewsk** [comment]
you have not specified a sec group

**Comment by nirandaperera** [comment]
We had the same issue with Jonathan yesterday. Only thing that resolved this issue was creating a new environment. I am wondering if this was related to an old openstack library.

**Comment by laszewsk** [comment]
here an example

 Cloud:    chameleon
    Name:     gregor-vm-39
    Label:    gregor-vm-39
    User:     cc
    IP:       129.114.26.219
    Image:    CC-Ubuntu18.04
    Size:     m1.medium
    Network:  e01ee12e-fd22-4b21-a050-d3e015f42bb1
    Public:   True
    Key:      gregor
    Location: None
    Timeout:  360
    Secgroup: default
    Group:    cloudmesh
    Groups:   ['cloudmesh']

see the secgroup is not None it must have a value
but there could be other issues, copy the exact command that you use so we can replicate this on the commandline to debug we need more info

**Comment by laszewsk** [comment]
he has secgroup = None
if he properly runs cms init secgroup would not be None, it should be default

so yes i recommend reinstall

**Comment by laszewsk** [comment]
Joshua is runnig on Windows. As i do not have windows its difficult for me to replicate :(

**Comment by laszewsk** [comment]
he also needs to delete the collections and call a new 

cms help 
cms init

just to be sure

the pytests do something special, e.g. they change the schema of the names for the vms, i wonder if somewhere a hardcoded name is used instead of the one form the schema, but first do the sec group and the init

**Comment by joshua-m-baker** [comment]
This is run from Ubuntu 18.04. I  will reinstall everything from scratch.

**Comment by laszewsk** [comment]
Looks like the test has a bug as the sec group is not set, please fix the test and before you start it set the sec group

**Comment by laszewsk** [comment]
test works with the suggested change, apparently chameleon no longer automatically accepts none and changes it to default.

**Comment by laszewsk** [comment]
i commit change now
